{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{include "cno.fullname" . }}
  labels: {{- include "cno.labels" . | nindent 4 }}
rules:
  - apiGroups: ["observability.shtsukada.dev"]
    resources:
      - grpcburners
      - grpcburners/status
      - grpcburners/finalizers
      - observabilityconfigs
      - observabilityconfigs/status
      - observabilityconfigs/finalizers
    verbs: ["get","list","watch","create","update","patch","delete"]

  - apiGroups: ["apps"]
    resources: ["deployments","replicasets"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods","services","endpoints","events","configmaps","secrets"]
    verbs: ["*"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["*"]
{{- end }}
