{{- /*
Deployment template (nil-safe)

- 依存ヘルパーは _helpers.tpl の
  cloudnative-observability-operator.{fullname,labels,selectorLabels,serviceAccountName}
- .Values が未定義/型不一致でも lint で落ちないよう、hasKey/kindIs/ternary でガード
*/ -}}

{{- $vals := .Values -}}

{{- /* replicaCount */ -}}
{{- $replicas := (hasKey $vals "replicaCount") | ternary $vals.replicaCount 1 -}}

{{- /* image */ -}}
{{- $img := (and (hasKey $vals "image") (kindIs "map[string]interface {}" $vals.image)) | ternary $vals.image (dict) -}}
{{- $repo := (hasKey $img "repository") | ternary $img.repository "ghcr.io/stsukada/cloudnative-observability-operator" -}}
{{- $tag  := (hasKey $img "tag")        | ternary $img.tag        .Chart.AppVersion -}}
{{- $pull := (hasKey $img "pullPolicy") | ternary $img.pullPolicy "IfNotPresent" -}}

{{- /* operator (env/args/resources など) */ -}}
{{- $op := (and (hasKey $vals "operator") (kindIs "map[string]interface {}" $vals.operator)) | ternary $vals.operator (dict) -}}
{{- $env := (and (hasKey $op "env") (kindIs "[]interface {}" $op.env)) | ternary $op.env (list) -}}
{{- $args := (and (hasKey $op "args") (kindIs "[]interface {}" $op.args)) | ternary $op.args (list) -}}
{{- $res := (and (hasKey $op "resources") (kindIs "map[string]interface {}" $op.resources)) | ternary $op.resources (dict) -}}
{{- $sec := (and (hasKey $op "securityContext") (kindIs "map[string]interface {}" $op.securityContext)) | ternary $op.securityContext (dict) -}}
{{- $podsec := (and (hasKey $op "podSecurityContext") (kindIs "map[string]interface {}" $op.podSecurityContext)) | ternary $op.podSecurityContext (dict) -}}
{{- $imagePullSecrets := (and (hasKey $vals "imagePullSecrets") (kindIs "[]interface {}" $vals.imagePullSecrets)) | ternary $vals.imagePullSecrets (list) -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudnative-observability-operator.fullname" . }}
  labels:
    {{- include "cloudnative-observability-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ $replicas }}
  selector:
    matchLabels:
      {{- include "cloudnative-observability-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cloudnative-observability-operator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "cloudnative-observability-operator.serviceAccountName" . }}
      {{- with $imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $podsec }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: manager
          image: {{ printf "%s:%s" $repo $tag | quote }}
          imagePullPolicy: {{ $pull }}
          ports:
            # controller-runtime metrics (デフォルト https/8443)
            - name: https
              containerPort: 8443
              protocol: TCP
            # health probe (kubebuilder 既定 8081)
            - name: health
              containerPort: 8081
              protocol: TCP
          args:
            {{- if $args }}
            {{- toYaml $args | nindent 12 }}
            {{- else }}
            - --metrics-bind-address=:8443
            - --health-probe-bind-address=:8081
            {{- end }}
          {{- with $env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $sec }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $res }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: operator-config
              mountPath: /etc/operator
              readOnly: true
      volumes:
        - name: operator-config
          configMap:
            name: {{ include "cloudnative-observability-operator.fullname" . }}-config
            optional: true
