apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudnative-observability-operator.fullname" . }}
  labels:
    {{- include "cloudnative-observability-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "cloudnative-observability-operator.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
