{{- /*
ServiceAccount:
  - .Values.serviceAccount.create が true のときだけ作成
  - name/annotations/automountServiceAccountToken はオプション
  - ヘルパーは _helpers.tpl の cloudnative-observability-operator.* を使用
*/ -}}

{{- $vals := .Values -}}
{{- $sa := (and (hasKey $vals "serviceAccount") (kindIs "map[string]interface {}" $vals.serviceAccount)) | ternary $vals.serviceAccount (dict) -}}
{{- $create := (hasKey $sa "create") | ternary $sa.create true -}}
{{- $name := include "cloudnative-observability-operator.serviceAccountName" . -}}
{{- $ann := (and (hasKey $sa "annotations") (kindIs "map[string]interface {}" $sa.annotations)) | ternary $sa.annotations (dict) -}}
{{- $automount := (hasKey $sa "automountServiceAccountToken") | ternary $sa.automountServiceAccountToken true -}}

{{- if $create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  labels:
    {{- include "cloudnative-observability-operator.labels" . | nindent 4 }}
  {{- with $ann }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $automount }}
{{- end }}
