apiVersion: v1
kind: Service
metadata:
  name: {{ include "cno.fullname" . }}
  labels:
    {{- include "cno.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "cno.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
