version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - errcheck
    - unused
    - goconst
    - gocritic
    - revive
    - gosec

  # 旧 linters-settings → v2 は linters.settings
  settings:
    revive:
      severity: warning
    gosec:
      excludes:
        - G104
        - G306
        - G404
    goconst:
      min-len: 3
      min-occurrences: 3

  # 旧 skip-files/dirs, issues.exclude-* → v2 は linters.exclusions.*
  exclusions:
    # 生成ファイル扱いの厳しさ（必要に応じて lax に）
    generated: strict
    # よくある誤検知のプリセット
    presets:
      - common-false-positives
      - std-error-handling

    # パス単位の除外（解析はするが報告しない）
    paths:
      - "^bin/"
      - "^vendor/"
      - "zz_generated.*\\.go"

    # ルール単位の除外（テストでは一部リンタを緩める等）
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - funlen
      - path: zz_generated.*\.go
        linters:
          - revive
          - gofmt
          - gocritic
          - gosec
