image:
  repository: ghcr.io/shtsukada/cloudnative-observability-operator
  tag: "v0.1.0"
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests: { cpu: 50m, memory: 128Mi }
  limits: { cpu: 300m, memory: 512Mi }

operator:
  env:
    - name: ZAP_LOG_LEVEL
      value: "info"

managedApp:
  image: ghcr.io/shtsukada/grpc-burner
  tag: "v0.1.0"
  replicas: 1
  otlpEndpoint: "http://otel-collector.monitoring:4317"
  env:
    - name: MODE
      value: "cpu"
    - name: QPS
      value: "10"
  ports:
    - name: grpc
      containerPort: 50051

service:
  type: ClusterIP
  port: 8080
  annotations: {}

serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s
  additionalLabels: {}

rbac:
  create: true
  namespaced: false

serviceAccount:
  create: true
  name: ""
  annotations: {}

installCRDs: true

leaderElection:
  enabled: true

security:
  podSecurityContext:
    runAsNonRoot: true
    enabledFixedIDs: false
    runAsUser: 65532
    runAsGroup: 65532
    fsGroup: 65532
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]

networkPolicy:
  enabled: true
  prometheusNamespace: "monitoring"
  metricsPort: 8080
  otlp:
    inCluster:
      enabled: true
      namespace: "monitoring"
      podSelector:
        matchLabels:
          app.kubernetes.io/name: "otel-collector"
      port: 4317
    external:
      enabled: false
      ipBlockCIDRs: ["0.0.0.0/0"]
      port: 4317
