image:
  repository: ghcr.io/shtsukada/cloudnative-observability-operator
  tag: "v0.1.0"
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests: { cpu: 50m,memory: 128Mi }
  limits: { cpu: 300m, memory: 512Mi }

operator:
  env:
    - name: ZAP_LOG_LEVEL
      value: "info"

managedApp:
  image: ghcr.io/shtsukada/grpc-burner
  tag: "v0.1.0"
  replicas: 1
  otlpEndpoint: "http://otel-collector.monitoring:4317"
  env:
    - name: MODE
      value: "cpu"
    - name: QPS
      value: "10"
  ports:
    - name: grpc
      containerPort: 50051

service:
  type: ClusterIP
  port: 8080
  annotations: {}

serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s
  additionalLabels: {}

rbac:
  create: true

serviceAccount:
  create: true
  name: ""
  annotations: {}

installCRDs: true

leaderElection:
  enabled: true

podSecurityContext:
  runAsNonRoot: true
  seccompProfile: { type: RuntimeDefault }

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]
