---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - observability.shtsukada.dev
  resources:
  - grpcburners
  - observabilityconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - observability.shtsukada.dev
  resources:
  - grpcburners/finalizers
  - observabilityconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - observability.shtsukada.dev
  resources:
  - grpcburners/status
  - observabilityconfigs/status
  verbs:
  - get
  - patch
  - update
