---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - observability.shtsukada.dev
  resources:
  - observabilityconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - observability.shtsukada.dev
  resources:
  - observabilityconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - observability.shtsukada.dev
  resources:
  - observabilityconfigs/status
  verbs:
  - get
  - patch
  - update
