---
name: lint (operator)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run yamllint
        run: yamllint .
      - name: Run markdownlint
        run: npx --yes markdownlint-cli2 **/*.md
      - name: Validate JSON
        run: |
          set -e
          find . -type f -name "*.json" -print0 | xargs -0 -I{} sh -c 'jq . "{}" >/dev/null' || true

      - name: Setup Go
        if: hashFiles('go.mod') != ''
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: golangci-lint
        if: hashFiles('go.mod') != '' && hashFiles('**/*.go') != ''
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61
          args: --timeout 5m

      - name: Count Go files
        id: list_go_files
        run: |
          n=$(git ls-files '*.go' | wc -l | tr -d ' ')
          echo "count=$n" >> "$GITHUB_OUTPUT"
          echo "Go files: $n"

      - name: go test
        if: hashFiles('go.mod') != '' && ${{ steps.list_go_files.outputs.count != '0' }}
        run: go test ./... -count=1
